name: UART Driver Tests

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: UART Driver Test
    runs-on: ubuntu-24.04
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure Rust toolchain
        run: |
          rustup toolchain install stable
          rustup default stable
          rustup target add riscv32imac-unknown-none-elf
      
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
      
      - name: Install QEMU
        run: |
          sudo apt update
          sudo apt install -y qemu-system-riscv32
      
      - name: Build project
        run: cargo build --release
      
      - name: Build tests
        working-directory: tests
        run: cargo build --release
      
      - name: Run basic tests
        working-directory: tests
        run: cargo run --release
      
      - name: Build host verification
        working-directory: tests/host_test
        run: cargo build --release
      
      - name: Run host verification
        working-directory: tests/host_test
        run: cargo run --release
